version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ../web-voc-data/db:/data/db
    ports:
      - "${MONGO_HOST_PORT:-27021}:27017"
    ## add --quiet to reduce log verbosity
    ## Suppress verbose WiredTiger messages
    command: [
      "mongod",
      "--quiet",
      "--logpath", "/dev/null",
      "--setParameter", "quiet=1",
      "--setParameter", "logLevel=0"
    ]

  api:
    build: .
    container_name: gs1-web-vocabulary-api
    ports:
      - "7087:7087"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/masterdata
      - PORT=${PORT:-7087}
      - NODE_ENV=${NODE_ENV:-development}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:7087}
      - API_KEY=${API_KEY}
